language: java
script:
  - mvn package -Dspark.version=${SPARK}
env:
  matrix:
    - SPARK=2.3.2
    - SPARK=2.1.0
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    - cedric.zhuang@memverge.com
    - yue.li@memverge.com
    - sheperd.huang@memverge.com
    - haiyan.wang@memverge.com
